import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }

  return (
    <html lang="en">
      <body className={lato.className}>
        <Toaster />
        <main className="flex min-h-screen">
          <aside className="bg-white p-4 w-48 shadow">
            <div className="rounded-full overflow-hidden w-24 mx-auto">
              <Image
                src={session.user.image}
                alt={"avatar"}
                width={256}
                height={256}
              />
            </div>
            <div className="text-center">
              <AppSidebar />
            </div>
          </aside>
          <div className="grow">
            <div className="bg-white m-16 p-4 shadow">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
